apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: sales-training-pipeline

  annotations:
    scenarios.ai.sap.com/name: "Sales Prediction"
    executables.ai.sap.com/name: "Train Sales Model"

  labels:
    scenarios.ai.sap.com/id: "sales-prediction-scenario"
    ai.sap.com/version: "1.0"

spec:
  entrypoint: train

  templates:

  - name: train

    container:
      image: docker.io/python:3.10

      command:
        - python

      args:
        - train.py
