apiVersion: ai.sap.com/v1alpha1
kind: WorkflowTemplate
metadata:
  name: demo-training-workflow
  annotations:
    scenarios.ai.sap.com/id: "demo-scenario"
    scenarios.ai.sap.com/name: "Demo Scenario"
    executables.ai.sap.com/id: "train-executable"
    executables.ai.sap.com/name: "Train Executable"
spec:
  templates:
    - name: main
      container:
        image: "alpine:latest"
        command: ["/bin/sh", "-c"]
        args: ["echo 'Sync Successful'"]
