apiVersion: ai.sap.com/v1alpha1
kind: WorkflowTemplate
metadata:
  name: caig-certification-test-v1
  annotations:
    scenarios.ai.sap.com/id: "learning-scenario"
    scenarios.ai.sap.com/name: "Learning Journey Scenario"
    executables.ai.sap.com/id: "learning-exec"
    executables.ai.sap.com/name: "Learning Executable"
spec:
  templates:
    - name: main
      container:
        image: "alpine:latest"
        command: ["/bin/sh", "-c"]
        args: ["echo 'Sync Success'"]
